[package]
name = "arbscan"
version = "0.2.0"
edition = "2024"
rust-version = "1.95"
description = "Utility for extracting OEM Anti-Rollback (ARB) metadata from Qualcomm bootloader images"
license = "Apache-2.0"
repository = "https://github.com/syedinsaf/arbscan"
readme = "README.md"

keywords = ["android", "qualcomm", "arb", "bootloader"]
categories = ["command-line-utilities"]
[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
debug = false
panic = "abort"
overflow-checks = true
incremental = false
